CREATE SCHEMA IF NOT EXISTS hcodedb;

CREATE TABLE IF NOT EXISTS hcodedb.ALGORITHM (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (ID));

CREATE TABLE IF NOT EXISTS hcodedb.COMPANY (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE INDEX UKrf676d3s4bqqyh8dud0uv1gof (NAME ASC));

CREATE TABLE IF NOT EXISTS hcodedb.ROLE (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE INDEX UK_fpfqgk4iamsjdmiu229j6vjjt (NAME ASC));

CREATE TABLE IF NOT EXISTS hcodedb.SESSION (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (ID));

CREATE TABLE IF NOT EXISTS hcodedb.TOPIC (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (ID));

CREATE TABLE IF NOT EXISTS hcodedb.USER (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  CREATED_AT DATETIME NOT NULL,
  UPDATED_AT DATETIME NOT NULL,
  EMAIL VARCHAR(40) NULL DEFAULT NULL,
  FIRST_NAME VARCHAR(20) NULL DEFAULT NULL,
  LAST_NAME VARCHAR(20) NULL DEFAULT NULL,
  LOGIN VARCHAR(40) NULL DEFAULT NULL,
  PASSWORD VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE INDEX UKm6gjtxi6t4thhq8x960qif5cy (LOGIN ASC),
  UNIQUE INDEX UKejfk3g58oxsgbb4ju3u4fhivk (EMAIL ASC));

CREATE TABLE IF NOT EXISTS hcodedb.USER_ROLE (
  USER_ID BIGINT(20) NOT NULL,
  ROLE_ID BIGINT(20) NOT NULL,
  PRIMARY KEY (USER_ID, ROLE_ID),
  INDEX FKn1rn9qodd3u4le8uf3kl33qe3 (ROLE_ID ASC),
  CONSTRAINT FKa8x5mvctia7u43u2mm3hyy5bm
    FOREIGN KEY (USER_ID)
    REFERENCES hcodedb.USER (ID),
  CONSTRAINT FKn1rn9qodd3u4le8uf3kl33qe3
    FOREIGN KEY (ROLE_ID)
    REFERENCES hcodedb.ROLE (ID));